CREATE TABLE USERS
(
    EMAIL      VARCHAR(100) PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(100)             NOT NULL,
    LAST_NAME  VARCHAR(100),
    DOB        DATE                     NOT NULL,
    GENDER     ENUM ('Male', 'Female')  NOT NULL
);

CREATE TABLE CREDENTIALS
(
    EMAIL         VARCHAR(100) PRIMARY KEY NOT NULL,
    PASSWORD_HASH VARCHAR(60)              NOT NULL,
    CONSTRAINT FK__USERS_CREDENTIALS FOREIGN KEY (EMAIL) REFERENCES USERS (EMAIL) ON DELETE CASCADE
);
